### ISSUE TITLE
running node-wot

### ISSUE THREAD

**Issue by moniwe** [thingweb/node-wot#63]
i followed the steps in the readme file. but when i try to run the node wot-servient in a cmd window on windows i only get this:

```
...\node-wot\examples\scripts>node wot-servient
module.js:473
      throw err;
      ^

Error: Cannot find module '...\node-wot\examples\scripts\wot-servient'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:453:25)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
```

do have any suggestion how i could get it running?

**Comment by egekorkan** [comment]
Do not use the node command with it. If you use the node command node.js will look for a script called wot-servient. wot-servient runs all the scripts in the directory you call wot-servient. You can think wot-servient as a command.

If you don't want to use wot-servient, check the examples in the packages folder

**Comment by moniwe** [comment]
unfortunately my understanding of node.js is quite low. I also tried typing wot-servient but this command seems to be unknown, that's why i thought calling node wot-servient would be correct. do i have to configure something that wot-servient gets known as command?

**Comment by egekorkan** [comment]
So one thing you can do is checking if you have errors on executing the last step of the installation, the optional step. Otherwise wot-servient basically calls the script found at node-wot/packages/node-wot/dist/command-line-tool/wot-servient.js  . So if you call this script by using the command node node-wot/packages/node-wot/dist/command-line-tool/wot-servient.js in the folder where you have the script you want to run (where examples are for example). However if you want to do anything more than just a demo please check the examples at node-wot/packages/node-wot-servient-examples/   . Feel free to ask questions on this.

**Comment by moniwe** [comment]
since i could not run the tsc command successfully anymore on windows, i tried it on a lubuntu vm.  when i execute `sudo npm run link` i get the following

```
...
lerna success - raspberry-demo-servient

> node-wot-root@0.3.0-SNAPSHOT.2 link /home/anubis/Schreibtisch/node-wot/node-wot
> lerna-run npm link

command:  npm link
packages: ["integration-tests","node-wot","node-wot-content-serdes","node-wot-helpers","node-wot-protocol-coap","node-wot-protocol-file","node-wot-protocol-http","node-wot-protocols","node-wot-servient-examples","node-wot-td-tools","raspberry-demo-servient"]
npm ERR! code E404
npm ERR! 404 Not Found: node-wot@0.3.0-SNAPSHOT.2

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/anubis/.npm/_logs/2017-10-04T11_54_07_752Z-debug.log
```

**Comment by moniwe** [comment]
the log file contains the following

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'link' ]
2 info using npm@5.3.0
3 info using node@v8.6.0
4 verbose linkPkg /home/anubis/Schreibtisch/node-wot/node-wot/packages/integration-tests
5 verbose link build target /usr/lib/node_modules/node-wot-integration-tests
6 verbose npm-session 675b8c4781153b50
7 silly install runPreinstallTopLevelLifecycles
8 silly preinstall node-wot-integration-tests@0.3.0-SNAPSHOT.2
9 info lifecycle node-wot-integration-tests@0.3.0-SNAPSHOT.2~preinstall: node-wot-integration-tests@0.3.0-SNAPSHOT.2
10 silly install loadCurrentTree
11 silly install readLocalPackageData
12 silly install loadIdealTree
13 silly install cloneCurrentTreeToIdealTree
14 silly install loadShrinkwrap
15 silly install loadAllDepsIntoIdealTree
16 http fetch GET 404 https://registry.npmjs.org/node-wot-protocol-coap 1264ms
17 silly fetchPackageMetaData error for node-wot-protocol-coap@0.3.0-SNAPSHOT.2 404 Not Found: node-wot-protocol-coap@0.3.0-SNAPSHOT.2
18 http fetch GET 404 https://registry.npmjs.org/node-wot 1319ms
19 silly fetchPackageMetaData error for node-wot@0.3.0-SNAPSHOT.2 404 Not Found: node-wot@0.3.0-SNAPSHOT.2
20 http fetch GET 404 https://registry.npmjs.org/node-wot-protocol-http 1541ms
21 silly fetchPackageMetaData error for node-wot-protocol-http@0.3.0-SNAPSHOT.2 404 Not Found: node-wot-protocol-http@0.3.0-SNAPSHOT.2
22 http fetch GET 404 https://registry.npmjs.org/node-wot-protocols 1735ms
23 silly fetchPackageMetaData error for node-wot-protocols@0.3.0-SNAPSHOT.2 404 Not Found: node-wot-protocols@0.3.0-SNAPSHOT.2
24 http fetch GET 404 https://registry.npmjs.org/node-wot 323ms
25 silly fetchPackageMetaData error for node-wot@0.3.0-SNAPSHOT.2 404 Not Found: node-wot@0.3.0-SNAPSHOT.2
26 http fetch GET 404 https://registry.npmjs.org/node-wot-protocols 1093ms
27 silly fetchPackageMetaData error for node-wot-protocols@0.3.0-SNAPSHOT.2 404 Not Found: node-wot-protocols@0.3.0-SNAPSHOT.2
28 http fetch GET 404 https://registry.npmjs.org/node-wot-protocol-coap 1152ms
29 silly fetchPackageMetaData error for node-wot-protocol-coap@0.3.0-SNAPSHOT.2 404 Not Found: node-wot-protocol-coap@0.3.0-SNAPSHOT.2
30 http fetch GET 404 https://registry.npmjs.org/node-wot-protocol-http 1358ms
31 silly fetchPackageMetaData error for node-wot-protocol-http@0.3.0-SNAPSHOT.2 404 Not Found: node-wot-protocol-http@0.3.0-SNAPSHOT.2
32 verbose stack Error: 404 Not Found: node-wot@0.3.0-SNAPSHOT.2
32 verbose stack     at fetch.then.res (/usr/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:41:19)
32 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
32 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
32 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
32 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
32 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
32 verbose stack     at Async._drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
32 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
32 verbose stack     at Immediate.Async.drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
32 verbose stack     at runCallback (timers.js:781:20)
32 verbose stack     at tryOnImmediate (timers.js:743:5)
32 verbose stack     at processImmediate [as _immediateCallback] (timers.js:714:5)
33 verbose cwd /home/anubis/Schreibtisch/node-wot/node-wot/packages/integration-tests
34 verbose Linux 3.13.0-44-generic
35 verbose argv "/usr/bin/node" "/usr/bin/npm" "link"
36 verbose node v8.6.0
37 verbose npm  v5.3.0
38 error code E404
39 error 404 Not Found: node-wot@0.3.0-SNAPSHOT.2
40 verbose exit [ 1, true ]
```

**Comment by moniwe** [comment]
yesterday i also tried it on windows from scratch (without tsc since it is not listed at the main page anymore). it seems that besides node.js 8.5 i also have to install python but this does not seem to be all since 

```
...
lerna info Installing external dependencies
lerna ERR! execute Error: Command failed: npm install
lerna ERR! execute gyp ERR! build error
lerna ERR! execute gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
lerna ERR! execute gyp ERR! stack     at ChildProcess.onExit (C:\Users\wenger\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
...
```

**Comment by moniwe** [comment]
finally i found out that `npm install --global --production windows-build-tools` installs everything that is needed on windows. when running `npm run link` in an admin cmd I then get the same message than on linux

```
command:  npm link
packages: ["integration-tests","node-wot","node-wot-protocol-coap","node-wot-protocol-file","node-wot-protocol-http","node-wot-servient-examples","node-wot-td-tools"]
npm ERR! code E404
npm ERR! 404 Not Found: node-wot@0.3.0-SNAPSHOT.3

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Roaming\npm-cache\_logs\2017-10-05T06_42_51_971Z-debug.log
1 
```

**Comment by moniwe** [comment]
even if npm link shows an error the counter example works now with the suggested command in wondows cmd `node packages\node-wot-servient-examples\dist\command-line-tool\wot-servient.js examples\scripts\counter.js`

**Comment by moniwe** [comment]
finally i found out that `npm install --global --production windows-build-tools` installs everything that is needed on windows. when running `npm run link` in an admin cmd I then get the same message than on linux

```
command:  npm link
packages: ["integration-tests","node-wot","node-wot-protocol-coap","node-wot-protocol-file","node-wot-protocol-http","node-wot-servient-examples","node-wot-td-tools"]
npm ERR! code E404
npm ERR! 404 Not Found: node-wot@0.3.0-SNAPSHOT.3

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Roaming\npm-cache\_logs\2017-10-05T06_42_51_971Z-debug.log
1 
```

**Comment by moniwe** [comment]
how can i add an additional property to a running counter? i added the httpResquester to my firefox an tried to POST and PUT an json object, but it did not work.

currently i only see http for the counter example but coap seems to be supported. what do i have to do if i want to run the counter example with coap instead of http.

**Comment by mkovatsc** [comment]
I will add the Windows build tools hint to the README.

Properties or Interactions in general are not created through the WoT Interface (cf. REST interface when HTTP). They are added within the script; the server has the full control over this, unless you implement an action that creates new Properties, for instance...

The default servient currently only loads the HTTP binding. We probably extend this to CoAP and maybe WebSockets in the future. For now, you need to create your own servient with all the bindings you want.

**Comment by danielpeintner** [comment]
Did the updated README help?

> On Windows, install the build tools
> `npm install --global --production windows-build-tools`

**Comment by moniwe** [comment]
for me this worked ... i guess the issue can be closed
