### ISSUE TITLE
npm run link

### ISSUE THREAD

**Issue by amitnagar19** [thingweb/node-wot#64]
//Having sapwn sh ENOENT issue while working in windows

command:  npm link
packages: ["integration-tests","node-wot","node-wot-content-serdes","node-wot-helpers","node-wot-protocol-coap","node-wot-protocol-file","node-wot-protocol-http","node-wot-protocols","node-wot-servient-examples","node-wot-td-tools","raspberry-demo-servient"]
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn sh ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-wot-root@0.3.0-SNAPSHOT.2 link: `lerna-run npm link`

**Comment by mkovatsc** [comment]
Works after repackaging and with windows-build-tools installed.
